epochs: 1500
batch_size: 64
embed_size: 384
n_heads: 8
head_size: 48
block_size: 256
n_layers: 8
dropout: 0.2
lr: 0.0003
log_interval: 250
eval_epochs: 50
seed: 42
save_path: models/model.pt
save_interval: 250
